---
kind: pipeline
type: docker
name: build_tests

steps:

- name: install_and_build
  image: python:3.8
  volumes:
    - name: cache
      path: /root/.platformio
  env:
    - PLATFORMIO_CI_SRC=RFLink
  commands:
  - pip install -U platformio
  - pio update
#  - platformio lib install
  - pwd
  - ls -la
  - pio run --project-conf .travis.platformio.ini --environment ESP32_all_enabled


- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: .pio/build/ESP32_all_enabled/firmware.elf
  when:
    event: tag


volumes:
- name: cache
  host:
    path: /tmp/drone/pio_cache


